const types = {
  REPOSITORIES_RECEIVED_SUCCESS: 'REPOSITORIES_RECEIVED_SUCCESS',
  GET_REPOSITORIES: 'GET_REPOSITORIES',
  GET_REPOSITORIES_FAILED: 'GET_REPOSITORIES_FAILED',
};

export default types;
